### ISSUE TITLE
conflict with esformatter-quotes plugin

### ISSUE THREAD

**Issue by millermedeiros** [briandipalma/esformatter-use-strict#2]
> Currently if I have "esformatter-use-strict" plugin and "esformatter-quotes" plugin configured to use double quotes, I end up with "use strict" having single quotes in the resulting formatted code.
> @jmullo

this plugin should be using `stringBefore` instead of `stringAfter`, that way the quotes would be formatted properly. (Or it should be changed to accept the same config as `esformatter-quotes` - or have any other way to configure the quotes)

see: https://github.com/millermedeiros/esformatter/issues/415

**Comment by briandipalma** [comment]
Thanks for opening this, it takes the same config as `esformatter-quotes`.
